### ISSUE TITLE
Open Research Webinars event website

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/opensourceinnovation.eu#1]
Hi there,
The content template for this event is on the team drive on https://docs.google.com/document/d/11W7y8Cyvyazm6uzzARzNyixLNqUdmVdADfs2YB_MkxE/edit#. 

Let us know what additional information you need!

**Comment by chrisguindon** [comment]
Let's discuss this on Monday @flora8984461

**Comment by chrisguindon** [comment]
@sjkiwai Can you provide the design files that we must use for this new website?

**Comment by flora8984461** [comment]
TODO list for me:

- [x] header

   - title(✔)
   - subtitle(✔)
   - Tagline(✔)
   - Important links(✔ - register)

   - update header img and logo (✔) 

- [x] Registration (About the Event) 

   - About content (✔) - updated 
   - Important links ( what's the registeration link? )
   - End Date (✔)
   - End text (✔)

- [x] Speakers / Program Committee

   - User_display on front page with one speaker (✔)
   - Program Committee? 
   - A page to display all speakers and User_display will hook to the person you clicked on? 

- [x] Agenda
   - default fake content created (✔)
   - Does session Information need? 

- [x] Sponsors
   - Co-organizers(✔ - copied from SAM IoT)

- [x] Webinar Series (use the homepage)

   - draft similar to jakartaOne, with upcoming events block and past events block (for now the content is empty) (✔)
   - More design... 

- [x] Fix no spacing in registeration link button

**Comment by flora8984461** [comment]
Hello, 
the previews are:
https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/
https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

based on what is in the google doc.

Thanks!
Yi

**Comment by sjkiwai** [comment]
> @sjkiwai Can you provide the design files that we must use for this new website?

I had included the files on the team drive - https://drive.google.com/drive/u/2/folders/1-v0CS-RkqVDhPuV3YK9Fwv5FI2x4usW1 
Final versions of the graphic, fonts, colours are on /WebinarSeriesDesigns. Let's use Bannerdesignblue.jpg first. That corresponds to Bannderdesign8c.jpg
![Bannerdesign blue 1980 x 950px](https://user-images.githubusercontent.com/7265777/98650739-98e22e80-2339-11eb-9dd5-9b00adb8a83d.jpg)
![Bannerdesign8c](https://user-images.githubusercontent.com/7265777/98650752-9da6e280-2339-11eb-9480-ba2c9083309a.jpg)
[Colors and Fonts.txt](https://github.com/EclipseFdn/opensourceinnovation.eu/files/5515981/Colors.and.Fonts.txt)
![Eclipse-Research-Logo-Horizontal](https://user-images.githubusercontent.com/7265777/98650789-ab5c6800-2339-11eb-8e23-e11734f9db1e.png)
![OW2 Logo](https://user-images.githubusercontent.com/7265777/98650794-ad262b80-2339-11eb-8775-85d6d162e11e.png)

**Comment by flora8984461** [comment]
@chrisguindon Do we want to replace the right nav to be the logo? Or we add both the two logos on left side? 🤔

> > @sjkiwai Can you provide the design files that we must use for this new website?
> 
> I had included the files on the team drive - https://drive.google.com/drive/u/2/folders/1-v0CS-RkqVDhPuV3YK9Fwv5FI2x4usW1
> Final versions of the graphic, fonts, colours are on /WebinarSeriesDesigns. Let's use Bannerdesignblue.jpg first. That corresponds to Bannderdesign8c.jpg
> ![Bannerdesign blue 1980 x 950px](https://user-images.githubusercontent.com/7265777/98650739-98e22e80-2339-11eb-9dd5-9b00adb8a83d.jpg)
> ![Bannerdesign8c](https://user-images.githubusercontent.com/7265777/98650752-9da6e280-2339-11eb-9480-ba2c9083309a.jpg)
> [Colors and Fonts.txt](https://github.com/EclipseFdn/opensourceinnovation.eu/files/5515981/Colors.and.Fonts.txt)
> ![Eclipse-Research-Logo-Horizontal](https://user-images.githubusercontent.com/7265777/98650789-ab5c6800-2339-11eb-8e23-e11734f9db1e.png)
> ![OW2 Logo](https://user-images.githubusercontent.com/7265777/98650794-ad262b80-2339-11eb-8775-85d6d162e11e.png)

**Comment by flora8984461** [comment]
Please check the previews:
homepage: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/
Open Research Webinars event page: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

The text are from https://docs.google.com/document/d/11W7y8Cyvyazm6uzzARzNyixLNqUdmVdADfs2YB_MkxE/edit?ts=5faae807#

Please let me know if the style is good for you.

And is there any preferred design for the homepage https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/? 

Thanks!

**Comment by chrisguindon** [comment]
> Please check the previews:
> homepage: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/

Can we style the content of the box to be similar to what we have here:
https://jakartaone.org/

> Open Research Webinars event page: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

Can you make sure that we are using the blue background style for sections with the  .featured-section-row-dark-bg class?

> @chrisguindon Do we want to replace the right nav to be the logo? Or we add both the two logos on left side?

Let's replace the right nav with the logo. I don't believe they want to link to eclipse.org top-menu links.

**Comment by flora8984461** [comment]
> > Please check the previews:
> > homepage: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/
> 
> Can we style the content of the box to be similar to what we have here:
> https://jakartaone.org/
> 
> > Open Research Webinars event page: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/
> 
> Can you make sure that we are using the blue background style for sections with the .featured-section-row-dark-bg class?
> 
> > @chrisguindon Do we want to replace the right nav to be the logo? Or we add both the two logos on left side?
> 
> Let's replace the right nav with the logo. I don't believe they want to link to eclipse.org top-menu links.

For now, I'm not using the blue background style for sections with the .featured-section-row-dark-bg class (that's speakers row). 
I think @sjkiwai will check the preview and let us know what bg they prefer for speakers row?

**Comment by chrisguindon** [comment]
@flora8984461 We must update the default styles of this site to match the branding styles that were provided to us.

This is what I am expecting:

<img width="1524" alt="Screen Shot 2020-11-11 at 8 56 22 AM" src="https://user-images.githubusercontent.com/893942/98820156-cc858d00-23fb-11eb-9983-3ff5bdf12c8d.png">

**Comment by flora8984461** [comment]
> @flora8984461 We must update the default styles of this site to match the branding styles that were provided to us.
> 
> This is what I am expecting:
> 
> <img alt="Screen Shot 2020-11-11 at 8 56 22 AM" width="1524" src="https://user-images.githubusercontent.com/893942/98820156-cc858d00-23fb-11eb-9983-3ff5bdf12c8d.png">

Got it

**Comment by flora8984461** [comment]
Please check the previews:
homepage: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/
Open Research Webinars event page: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

------------------------ Updated on Nov 11 -----------------------------
revision history 0.3

- Replace right nav with logo (Not sure should I also remove toolbar?)
- Adjust Homepage upcoming events block (Can someone provide me design and color theme for homepage?)
- Updated all button's default color
- Updated speaker's bg
- Modified the shortcode for past events to hide past events when no one

**Comment by flora8984461** [comment]
Updates of modification after meeting Nov 12:

- [x] - remove Brain IoT logo
- [x] - create a footer.html and remove some links
- [x] - remove "edit my account"
- [x] - remove "featured story"

Anything else? @chrisguindon

**Comment by chrisguindon** [comment]
@flora8984461 +1 but we need to wait for more instructions before we update the footer!

We also need to remove the featured story from the site.

**Comment by flora8984461** [comment]
> Updates of modification after meeting Nov 12:
> 
> * [x]  - remove Brain IoT logo
> * [x]  - create a footer.html and remove some links
> * [x]  - remove "edit my account"
> * [x]  - remove "featured story"
> 
> Anything else? @chrisguindon

Have done these updates.
I have created a [footer.html](https://github.com/EclipseFdn/opensourceinnovation.eu/pull/2/files#diff-1236858a4652b74ac20c849dced102285e73793914ce9093a079f5466bb7a938), but I did not remove any links. I will wait for more instructions.

And questions: @chrisguindon @sjkiwai 
- Do you need me to change "REGISTER NOW" button to "Agenda" or "Speakers" so that they hook to the related section? Since we have a "register now" button right after the header.

- Do you want me to link the "Code of Conduct" to https://events.eclipse.org/code-of-conduct/ instead of creating a page here? 

Thanks!
