### ISSUE TITLE
Add a BIO page

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/opensourceinnovation.eu#11]
**Describe the bug**
I tried to add the BIO page without success.
I could activate it by defining the subpage:
  {{< events/user_display event="open-research-webinars" year="2020" title="Speakers" source="speakers" imageRoot="/2020/december/images/speakers/" subpage="/speakers" displayLearnMore="false" />}}

I also could add the speaker page in the same folder as the _index.md but the links don't point me to the correct file.
Any help will be welcome

Here is the current status:

https://deploy-preview-10--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

and I attach the 2 files I have changed (I had to rename them for sharing):

[_index.md.txt](https://github.com/EclipseFdn/opensourceinnovation.eu/files/5596041/_index.md.txt)
[speakers.md.txt](https://github.com/EclipseFdn/opensourceinnovation.eu/files/5596042/speakers.md.txt)

**Comment by chrisguindon** [comment]
Thanks for the issue @phkrief!

@flora8984461 can you look into this please?
