### ISSUE TITLE
Updates to Open Research Webinars

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/opensourceinnovation.eu#23]
For Philippe

March 4th
- update DECODER title to:  "... software code exploration and analysis" => add 'software'
- remove link to Speaker Guidelines

Landing page
- add June 1st - save the date

**Comment by autumnfound** [comment]
@phkrief is this an issue still, or was it resolved and left open accidentally (just doing some issue clean up!)

**Comment by phkrief** [comment]
Thx for asking. Yes this issu is solved. 
Closing it
