### ISSUE TITLE
Google search results cannot display text

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/opensourceinnovation.eu#31]
Hi @chrisguindon 
If you do a google search on "open source research webinar", this site appears on page 2 with the note "no information is available for this page". See screenshots for explanation. Do you have a pointer on how we can fix this?

Thank you!

![Screen Shot 2021-04-15 at 11 14 14](https://user-images.githubusercontent.com/7265777/114853866-84242e00-9de4-11eb-883c-50a31fbe154b.png)
![Screen Shot 2021-04-15 at 11 14 58](https://user-images.githubusercontent.com/7265777/114853869-84bcc480-9de4-11eb-8481-c10ae506ac08.png)

**Comment by chrisguindon** [comment]
I am noticing an issue on our end. I will deploy a fix and let's revisit this in a week to see if the situation is improved!

**Comment by chrisguindon** [comment]
![Screenshot 2021-05-25 084350](https://user-images.githubusercontent.com/893942/119500054-6035ff80-bd35-11eb-9925-2fd0ab8eb322.png)

Looks like this is fixed now!
